### importing libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
# loading the dataset
data = pd.read_excel("Final_BCG.xlsx")

In [3]:
data.sample(10)

,Unnamed: 0,id,channel_sales,contract_dur,durfa_to_ren,acmod_dur,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,...,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,price_date,price_mid_peak_var,price_peak_fix,price_mid_peak_fix,churn
96337,96337,52a7dc941da31bd0f79fc0a5b01ecd50,foosdfpfkusacimwkcsosbicdxkicaua,11,10,0,36329,0,3181,3668.36,...,1,402.27,11,ldkssxwpmemidmecebumciepifcamkci,19.800,2015-08-01,0.074516,24.437330,16.291555,0
124559,124559,5fa443de7bd82539d38248249677ee86,lmkebamcaaclubfxadlmueccxoimlema,3,2,0,897536,553593,38224,0.00,...,2,0.00,4,lxidpiddsbxsbosboudacockeimpuepw,75.600,2015-08-01,0.065432,36.490689,8.367731,0
135345,135345,07160b57e8e685de4a0a60e356fffb50,foosdfpfkusacimwkcsosbicdxkicaua,4,3,2,1910,0,228,282.70,...,1,33.83,4,lxidpiddsbxsbosboudacockeimpuepw,13.150,2015-08-01,0.000000,0.000000,0.000000,0
107173,107173,e0e4624af640cb4284212752f82d1b29,foosdfpfkusacimwkcsosbicdxkicaua,5,4,0,13136,0,0,1953.10,...,1,183.95,4,ldkssxwpmemidmecebumciepifcamkci,13.200,2015-06-01,0.000000,0.000000,0.000000,0
53492,53492,805f818aa0eefcdfb763b0cd3b7206df,foosdfpfkusacimwkcsosbicdxkicaua,11,10,0,82696,0,5801,512.07,...,1,53.36,10,ldkssxwpmemidmecebumciepifcamkci,13.200,2015-04-01,0.000000,0.000000,0.000000,0
156641,156641,90a56b191d6a9780cbe0aa25b0c5d9e8,foosdfpfkusacimwkcsosbicdxkicaua,5,4,3,17811,0,3080,2628.50,...,2,211.43,4,lxidpiddsbxsbosboudacockeimpuepw,13.000,2015-06-01,0.000000,0.000000,0.000000,0
84494,84494,f1a6d9f2f6349049bbc4306a94ff6df2,lmkebamcaaclubfxadlmueccxoimlema,5,4,0,6207104,41532,558120,5036.60,...,2,393.57,5,lxidpiddsbxsbosboudacockeimpuepw,13.856,2015-06-01,0.000000,0.000000,0.000000,0
116437,116437,9d07e4d3891dc27a40d2ee303cdec1cb,foosdfpfkusacimwkcsosbicdxkicaua,6,5,5,11305,0,0,1649.06,...,1,110.03,5,lxidpiddsbxsbosboudacockeimpuepw,10.392,2015-02-01,0.000000,0.000000,0.000000,0
117198,117198,c42908cc26ccd8ff758fb4c9af2e0081,foosdfpfkusacimwkcsosbicdxkicaua,7,6,0,2822,0,0,419.93,...,1,37.81,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,2015-07-01,0.000000,0.000000,0.000000,1
3073,3073,1c55c6785645c643d564dd59ff96204b,foosdfpfkusacimwkcsosbicdxkicaua,7,6,0,7066,0,0,1059.18,...,1,103.87,7,ldkssxwpmemidmecebumciepifcamkci,13.200,2015-02-01,0.000000,0.000000,0.000000,0

### Data Exploration

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175149 entries, 0 to 175148
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   175149 non-null  int64
 1   id                           175149 non-null  object
 2   channel_sales                175149 non-null  object
 3   contract_dur                 175149 non-null  int64
 4   durfa_to_ren                 175149 non-null  int64
 5   acmod_dur                    175149 non-null  int64
 6   cons_12m                     175149 non-null  int64
 7   cons_gas_12m                 175149 non-null  int64
 8   cons_last_month              175149 non-null  int64
 9   forecast_cons_12m            175149 non-null  float64
 10  forecast_cons_year           175149 non-null  int64
 11  forecast_discount_energy     175149 non-null  int64
 12  forecast_meter_rent_12m      175149 non-null  float64
 13  change_energy_price_offpeak  175149 non-null  float64
 14  change_energy_price_peak     175149 non-null  float64
 15  change_power_price_offpeak   175149 non-null  float64
 16  has_gas                      175149 non-null  object
 17  imp_cons                     175149 non-null  float64
 18  margin_gross_pow_ele         175149 non-null  float64
 19  margin_net_pow_ele           175149 non-null  float64
 20  nb_prod_act                  175149 non-null  int64
 21  net_margin                   175149 non-null  float64
 22  num_years_antig              175149 non-null  int64
 23  origin_up                    175149 non-null  object
 24  pow_max                      175149 non-null  float64
 25  price_date                   175149 non-null  object
 26  price_mid_peak_var           175149 non-null  float64
 27  price_peak_fix               175149 non-null  float64
 28  price_mid_peak_fix           175149 non-null  float64
 29  churn                        175149 non-null  int64
dtypes: float64(13), int64(12), object(5)
memory usage: 40.1+ MB

In [7]:
# looking for duplicates in the data
data.duplicated().sum()

0

In [21]:
# number of unique variables in object columns
for column in data.select_dtypes("object"):#.drop("id", axis = 1).columns:
    print("*"*40)
    print(f"The number of unique values in the {column} column is: {data[column].nunique()}.\n With the value counts as follows:\n")
    print(f"{data[column].value_counts()}")
    print("*"*40)

****************************************
The number of unique values in the id column is: 14606.
 With the value counts as follows:

0e8df670a11a4f835b562bcfbafa6144    12
3eeca294a2985aaf51c282f9657e3068    12
327aac5866baf2bfe6a14c359a515aa7    12
b641db18102518188d9618d0756547ef    12
1b90ee21ac169fd4d14dad0394c8df01    12
                                    ..
9c9d8de40aee618b75f36e9b0f0586b6     9
3e459d61dc831e29f8a9a9a59f95efd2     8
c5dcd5c506e565aaabffa29bc1ec0a37     7
15b36e47cf04bf151e3f4438d12672e5     7
bf89f2d8c1b133a134fd93603cb4c947     7
Name: id, Length: 14606, dtype: int64
****************************************
****************************************
The number of unique values in the channel_sales column is: 7.
 With the value counts as follows:

foosdfpfkusacimwkcsosbicdxkicaua    125655
lmkebamcaaclubfxadlmueccxoimlema     22105
usilxuppasemubllopkaafesmlibmsdf     16486
ewpakwlliwisiwduibdlfmalxowmwpci     10712
sddiedcslfslkckwlfkdpoeeailfpeds       131
epumfxlbckeskwekxbiuasklxalciiuu        36
fixdbufsefwooaasfcxdxadsiekoceaa        24
Name: channel_sales, dtype: int64
****************************************
****************************************
The number of unique values in the has_gas column is: 2.
 With the value counts as follows:

f    143364
t     31785
Name: has_gas, dtype: int64
****************************************
****************************************
The number of unique values in the origin_up column is: 5.
 With the value counts as follows:

lxidpiddsbxsbosboudacockeimpuepw    85853
kamkkxfxxuwbdslkwifmmcsiusiuosws    51503
ldkssxwpmemidmecebumciepifcamkci    37757
usapbepcfoloekilkwsdiboslwaxobdp       24
ewxeelcelemmiwuafmddpobolfuxioce       12
Name: origin_up, dtype: int64
****************************************
****************************************
The number of unique values in the price_date column is: 12.
 With the value counts as follows:

2015-12-01    14604
2015-08-01    14604
2015-07-01    14601
2015-11-01    14599
2015-10-01    14597
2015-06-01    14596
2015-02-01    14596
2015-09-01    14593
2015-04-01    14592
2015-03-01    14591
2015-05-01    14590
2015-01-01    14586
Name: price_date, dtype: int64
****************************************

As each of the object columns contains values less than 15 in iteration, except for the ID column, we will exclude the ID column while encoding the rest of the columns.

For the price_date column we'll  extract a month price column, thus the resulting new data will be in machine readable format.

### Data Preprocessing and Feature Engineering

In [22]:
# creating a copy of the original data
data1 = data.copy()

In [29]:
# dropping the id column
data1.drop("id", axis = 1, inplace = True)

In [31]:
# replacing 1 for "t" and 0 for "f" in the has_gas column
data1["has_gas"] = data1["has_gas"].replace({"t": 1, "f": 0})

In [32]:
# converting the price_date column into month_price
data1["price_date"] = pd.to_datetime(data1["price_date"])

data1["month"] = data1["price_date"].dt.month

In [33]:
# dropping the price_date column
data1.drop("price_date", axis = 1, inplace = True)

In [34]:
data1.sample(5)

,Unnamed: 0,channel_sales,contract_dur,durfa_to_ren,acmod_dur,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,...,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,price_mid_peak_var,price_peak_fix,price_mid_peak_fix,churn,month
60215,60215,foosdfpfkusacimwkcsosbicdxkicaua,5,4,2,36775,47130,1885,3852.54,1885,...,2,547.99,4,lxidpiddsbxsbosboudacockeimpuepw,31.180,0.072612,24.437330,16.291555,0,3
72955,72955,foosdfpfkusacimwkcsosbicdxkicaua,7,6,0,4485,0,341,460.13,341,...,1,50.80,6,ldkssxwpmemidmecebumciepifcamkci,26.400,0.071536,24.339581,16.226389,0,6
82043,82043,usilxuppasemubllopkaafesmlibmsdf,4,3,2,23455,0,1739,2276.48,1739,...,1,286.08,4,ldkssxwpmemidmecebumciepifcamkci,17.321,0.072394,24.437330,16.291555,1,2
47366,47366,foosdfpfkusacimwkcsosbicdxkicaua,8,7,0,0,0,0,0.00,0,...,1,0.00,8,ldkssxwpmemidmecebumciepifcamkci,15.000,0.065678,36.490689,8.367731,0,9
43771,43771,foosdfpfkusacimwkcsosbicdxkicaua,12,11,10,78842,0,4571,2626.50,0,...,1,192.89,11,ldkssxwpmemidmecebumciepifcamkci,13.200,0.000000,0.000000,0.000000,0,11

In [36]:
# summary satatistics for int and float columns
data1.describe()

,Unnamed: 0,contract_dur,durfa_to_ren,acmod_dur,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,...,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,price_mid_peak_var,price_peak_fix,price_mid_peak_fix,churn,month
count,175149.000000,175149.000000,175149.000000,175149.000000,1.751490e+05,1.751490e+05,175149.000000,175149.000000,175149.000000,175149.000000,...,175149.000000,175149.00000,175149.000000,175149.000000,175149.000000,175149.000000,175149.000000,175149.000000,175149.000000,175149.000000
mean,87574.000000,5.318483,4.383319,1.594345,1.592606e+05,2.808072e+04,16095.518404,1868.343884,1399.782380,0.967028,...,24.564223,1.29230,189.245305,4.998276,18.134896,0.028270,9.458953,6.096434,0.097077,6.500911
std,50561.305487,1.695892,1.672747,2.017220,5.735413e+05,1.629400e+05,64376.741908,2387.560169,3248.331276,5.109025,...,20.233588,0.70978,311.846765,1.611801,13.535809,0.036065,12.133202,7.822250,0.296064,3.452020
min,0.000000,2.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.00000,0.000000,1.000000,3.300000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,43787.000000,4.000000,3.000000,0.000000,5.674000e+03,0.000000e+00,0.000000,494.980000,0.000000,0.000000,...,14.280000,1.00000,50.710000,4.000000,12.500000,0.000000,0.000000,0.000000,0.000000,4.000000
50%,87574.000000,5.000000,4.000000,0.000000,1.411500e+04,0.000000e+00,792.000000,1112.610000,314.000000,0.000000,...,21.640000,1.00000,112.500000,5.000000,13.856000,0.000000,0.000000,0.000000,0.000000,7.000000
75%,131361.000000,6.000000,5.000000,3.000000,4.076300e+04,0.000000e+00,3383.000000,2400.350000,1745.000000,0.000000,...,29.880000,1.00000,243.000000,6.000000,19.180000,0.072900,24.339581,16.226389,0.000000,10.000000
max,175148.000000,13.000000,12.000000,11.000000,6.207104e+06,4.154590e+06,771203.000000,82902.830000,175375.000000,30.000000,...,374.640000,32.00000,24570.650000,13.000000,320.000000,0.114102,36.490689,17.458221,1.000000,12.000000

#### Label Encoding

In [37]:
# Label Encoder Library importation
from sklearn.preprocessing import LabelEncoder

In [38]:
# encoding the remaining object columns
encoder = LabelEncoder()

for column in data1.select_dtypes("object").columns:
    data1[column] = encoder.fit_transform(data1[column])

In [40]:
data1.sample(6).T

,67620,58788,42842,156898,90205,16389
Unnamed: 0,67620.000000,58788.000000,42842.000000,156898.000000,90205.000000,16389.000000
channel_sales,3.000000,3.000000,3.000000,6.000000,3.000000,3.000000
contract_dur,7.000000,7.000000,6.000000,3.000000,6.000000,4.000000
durfa_to_ren,5.000000,6.000000,5.000000,2.000000,5.000000,3.000000
acmod_dur,6.000000,0.000000,4.000000,0.000000,5.000000,3.000000
cons_12m,10070.000000,860.000000,28458.000000,61.000000,5867.000000,37046.000000
cons_gas_12m,0.000000,0.000000,0.000000,0.000000,8228.000000,0.000000
cons_last_month,2467.000000,0.000000,3070.000000,33.000000,502.000000,3186.000000
forecast_cons_12m,1586.380000,127.590000,3001.790000,8.890000,802.430000,677.480000
forecast_cons_year,2467.000000,0.000000,3070.000000,33.000000,495.000000,604.000000
forecast_discount_energy,30.000000,0.000000,0.000000,0.000000,0.000000,28.000000
forecast_meter_rent_12m,16.780000,18.420000,130.320000,18.320000,18.260000,19.400000
change_energy_price_offpeak,0.002195,0.005309,0.013291,0.001878,0.005751,0.004502
change_energy_price_peak,0.000597,0.000000,0.006181,0.000000,0.000000,0.000000
change_power_price_offpeak,0.137832,-0.044447,0.122184,0.133332,-0.044448,-1.541448
has_gas,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
imp_cons,376.890000,0.000000,308.410000,4.740000,73.250000,113.130000
margin_gross_pow_ele,41.060000,10.030000,8.400000,34.270000,26.040000,36.360000
margin_net_pow_ele,41.060000,10.030000,8.400000,34.270000,26.040000,36.360000
nb_prod_act,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000
net_margin,74.020000,11.170000,355.200000,1.500000,85.180000,60.630000
num_years_antig,7.000000,6.000000,5.000000,4.000000,6.000000,4.000000
origin_up,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000
pow_max,13.856000,10.350000,25.000000,15.000000,10.392000,10.390000
price_mid_peak_var,0.000000,0.000000,0.074934,0.000000,0.000000,0.000000
price_peak_fix,0.000000,0.000000,24.437330,0.000000,0.000000,0.000000
price_mid_peak_fix,0.000000,0.000000,16.291555,0.000000,0.000000,0.000000
churn,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month,9.000000,3.000000,1.000000,11.000000,6.000000,10.000000

In [43]:
data1.columns

Index(['column_x', 'channel_sales', 'contract_dur', 'durfa_to_ren',
       'acmod_dur', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'change_energy_price_offpeak',
       'change_energy_price_peak', 'change_power_price_offpeak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'price_mid_peak_var', 'price_peak_fix', 'price_mid_peak_fix', 'churn',
       'month'],
      dtype='object')

In [42]:
# renaming the unnamed column 
data1.rename(columns={'Unnamed: 0': 'column_x'}, inplace=True)

#### Rearranging the columns

In [ ]:
new_column_order = ['contract_dur', 'channel_sales', 'durfa_to_ren',  'column_x', 
       'acmod_dur', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'change_energy_price_offpeak',
       'change_energy_price_peak', 'change_power_price_offpeak', 'has_gas', 'month',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'price_mid_peak_var', 'price_peak_fix', 'price_mid_peak_fix', 'churn']